---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarqube-conf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarqube-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarqube-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarqube-extensions
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: sonarqube
  labels:
    app: sonarqube
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: quay.io/davivcgarcia/ubi-sonarqube
          ports:
            - containerPort: 9000
              protocol: TCP
              name: http
          env:
            - name: SONARQUBE_JDBC_URL
              value: ''
            - name: SONARQUBE_JDBC_USERNAME
              value: ''
            - name: SONARQUBE_JDBC_PASSWORD
              value: ''
          volumeMounts:
            - name: conf
              mountPath: /opt/sonarqube/conf
            - name: data
              mountPath: /opt/sonarqube/data
            - name: logs
              mountPath: /opt/sonarqube/logs
            - name: extensions
              mountPath: /opt/sonarqube/extensions
          resources:
            requests:
              memory: "4096Mi"
              cpu: "2"
            limits:
              memory: "8912Mi"
              cpu: "4"
          startupProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 5
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 5
            periodSeconds: 15
      volumes:
        - name: conf
          persistentVolumeClaim:
            claimName: sonarqube-conf
        - name: data
          persistentVolumeClaim:
            claimName: sonarqube-data
        - name: logs
          persistentVolumeClaim:
            claimName: sonarqube-logs
        - name: extensions
          persistentVolumeClaim:
            claimName: sonarqube-extensions
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube
spec:
  selector:
    app: sonarqube
  ports:
  - protocol: TCP
    port: 9000
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: sonarqube
  annotations:
    openshift.io/host.generated: 'true'
spec:
  to:
    kind: Service
    name: sonarqube
    weight: 100
  port:
    targetPort: 9000
  wildcardPolicy: None
    